//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int userID { get; set; }

        [Required] // attributes 
        [RegularExpression(@"^[A-Z]+[A-z]{1,30}$")]
        public string fName { get; set; }

        [Required]
        [RegularExpression(@"^[A-Z]+[A-z]{1,30}$")]
        public string lName { get; set; }

        [Required]
        [RegularExpression(@"^([A-z0-9]{5,30})@([A-z]{3,10}).([a-z]{2,3})$")]
        public string email { get; set; }

        [Required]
        [RegularExpression(@"^\d{3}-\d{3}-\d{4}$")]
        public string phone { get; set; }

        [Required]
        [RegularExpression(@"^[A-z0-9]{5,30}$")]
        public string password { get; set; }
        

        public User()
        {
            fName = "";
            lName = "";
            email = "";
            phone = "";
            password = "";
        }
        public User(string fn, string ln, string em, string ph, string pa)
        {
            fName = fn;
            lName = ln;
            email = em;
            phone = ph;
            password = pa;
        }

    }
}
