//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class User
    {
        public int userID { set; get; }

        [Required] // attributes 
        [RegularExpression(@"^[A-Z]+[A-z]{1,30}$")]
        public string fName { set; get; }

        [Required]
        [RegularExpression(@"^[A-Z]+[A-z]{1,30}$")]
        public string lName { set; get; }

        [Required]
        [RegularExpression(@"^([A-z0-9]{5,30})@([A-z]{3,10}).([a-z]{2,3})$")]
        public string email { set; get; }

        [Required]
        [RegularExpression(@"^\d{3}-\d{3}-\d{4}$")]
        public string phone { set; get; }

        [Required]
        [RegularExpression(@"^[A-z0-9]{5,30}$")]
        public string password { set; get; }
    }
}
    

